version: '3'

volumes:
  pg_data:
  logs:



services:
  db:
    restart: always
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    restart: always
    image: qwertttyyy/bot
    env_file: .env
    depends_on:
      - db
    volumes:
      - logs:/app/bot/log/logs

  strava_app:
    restart: always
    image: qwertttyyy/strava_app
    env_file: .env
    depends_on:
      - db

    ports:
      - 8000:8000